### ISSUE TITLE
Half texel offset bug in `tex3D` emulation

### ISSUE THREAD

**Issue by h3r2tic** [SergeyMakeev/tony-mc-mapface-fuse#1]
Hey!

Thanks for porting Tony to Resolve! 😀

I've noticed that there's a slight bug in the way the 3D LUT is emulated via manual interpolation of two 2D fetches.

```
    local pz = uz * LUT_DIMS

    -- integer part
    local iz = math.floor(pz)

    -- fractional part
    local fz = pz - iz
```

`uv` is earlier calculated to be _centered_ on texels. The UV coordinate of a texel center is in its middle, therefore the center of texel [0, 0] is the UV [0.5, 0.5] / LUT_DIMS, center of texel [1, 0] is the UV [1.5, 0.5] / LUT_DIMS, and so on.

so if we take `uz` corresponding to texel 0, the value is `0.5 / LUT_DIMS`. `pz` becomes `0.5`. Then `iz` is `0`, and `fz` is `0.5`. This means that even though the UV coordinate was _centered_ on the Z component of the UV coordinate, the code ends up interpolating at 50% between texel 0 and 1.

This produces a slight but constant linear blue lift in the output image. It should be easy to see if you just feed it a black input, and it's even visible in the screenshots you have in the README.

The fix?

```
local pz = uz * LUT_DIMS - 0.5
```

or a bit cleaner semantically:

```
    local pz = uz * LUT_DIMS

    -- integer part
    local iz = math.floor(pz - 0.5)

    -- fractional part
    local fz = pz - 0.5 - iz
```

Huzzah!

// P.S. I haven't tested this in Resolve, but an equivalent fix worked for someone who had ported the fuse code to GLSL

**Comment by SergeyMakeev** [comment]
Good catch! I'll fix that asap

**Comment by SergeyMakeev** [comment]
Fixed
Thanks again!

**Comment by h3r2tic** [comment]
Sweet, thanks for applying the fixy fix!
